language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: mphartman-github
    token:
      secure: aaWwBl4P5Rgz3HaUjK0gFRzUx1whXcV8zyjZddVSnU7Uq7/J//jkx18gZNVctXzyoMh+GBJxyFlSxLnPhP/tupkDboqLR13j86i0slE6gXrheZopU8wDIUXl3XkZCQc9/bA0T6QWITwy2S5tUfB+KQnN/K+X+mSrVoHBF0AOIm6HZPsVvQ9nyjalb5+fvHbO2cldwaAFGN3UPzx0tyVqKylKBbvMpcudzHi5jcPpg0snQ+HwPCSstapw4auHeJrToT5lzuKUbM339+PFI29mQHB3b0MZkRC7nYITmtjEr3hYDlzvfMrIs8o1M41ItSKUfsWoAyMmf7r8on/2mPv5nPPkShLjh+o0KLJnNpL7/icirkG/ITAA8Aj0Z2ZkTgMbFvhmHzKjFVgbpmkPftRWdBr9AdYZFKcUKNUOvJ8KUTe0dUV6gijPRmWgNNMqFbseE5VwIBTgQuAU3T92zCFuEiDV2UmXQogm+ueFs69VqQXAuQJq1gPItxd8qqGfoM7v/9f28WA7iAON+nmjkDD+bdIPF63OFCcyUGKIMatDYc7OAbLY4bhv+zkcanKljZUEMA29mt78LEKjnSCfxP6ZzmT7pHXwKyooqYl3qp6VmjiQmzFMa0hiZvx+11gbrEBQiIju29w3BpOpn5nwaFSla0Z2lTPvp/mj1uQUWd5gEMY=
jdk:
- openjdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA5AISIHAIKLQIXM44
  secret_access_key:
    secure: cwVA1pbHVDt2NXamJ3/0LRgzRVo9+KNnNFIu/bcnOrr7uD1Hpyaelf2WvTnRmbHsEBNIcfYMeR1fNKuOWbJ5JmeW1/jPb3KEBVKaoj6lWEGnBrS10CPhBX8SkimZmRoFQr5Uzd8LCCd88Os5tJhKBptvhDSpB3ulz/F7pS7AsZFM4O+L7ygN4WaDpyRH8ksRoXl7kS+GT5lCmCPfTiWSyExETjrCQfXJe/4DTCi+gWWuKcc0op1UUXW92tFCLfDV6qeu+0TwQS8iddgIx+nL862YkmvsL6uUvlicquCnYoROpJdiqKsoyZYGqslae6+pbWJPowR8VK7sL3yQ49s8cN3k5UG78ljis3Om3yVNTcYqKuGDB9G8oEAvShjP1X+lVL65SNT/x/g3M1IWVQmY7Cgfx4cOoqdqxM1zVFKYPX3jTisH8vw6OOLkw27kaQe+fY9vLRhgeshBqXzw8+sOw2r/81ItmniYNLAzQ1LDETaxAPA5H2bGd6d8B/CCAz5j0zCmUfFiImxDh3k8Dso+FquskLCzbJ8ft8AkaAbLpZEjYwhOr3bUyG+7AWJxALNbUuwHbtgP6hgZQQDjOYNyRrHANhIs/3Zeh6BFjAiqvGHqggvIwPyy3KWwnZi01HFmYhCrVZRsrVgrXoukFfobHhKaz8UwZyLC++AMVEZ4uIQ=
  region: us-east-1
  app: adventureland-api
  env: dev
  on:
    repo: mphartman/adventureland
    branch: master
