branch-defaults:
  default:
    environment: adventureland-api-dev
    group_suffix: null
  master:
    environment: null
deploy:
  artifact: api/target/adventureland-api.zip
environment-defaults:
  adventureland-api-dev:
    branch: null
    repository: null
global:
  application_name: adventureland-api
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Java 8
  default_region: us-east-1
  include_git_submodules: true
  profile: null
  sc: git
  workspace_type: Application
